# Local server port
server.port=8080

# No context-path: let Spring Boot/Tomcat decide
# server.servlet.context-path=

# Swagger docs
springdoc.api-docs.path=/api-docs

# PostgreSQL DB
#spring.datasource.url=jdbc:postgresql://103.133.215.182:5432/Procurement
#spring.datasource.username=mmudevdb
#spring.datasource.password=mmudevdb

spring.datasource.url=jdbc:postgresql://localhost:5432/Procurement
spring.datasource.username=postgres
spring.datasource.password=boba
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=my_super_secret_key_which_should_be_very_long_1234567890
jwt.expiration=28800000

# CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=Authorization,Content-Type
spring.web.cors.exposed-headers=Authorization


vendor.registration.fee.enabled=true
vendor.registration.fee.amount=5000


# Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deevan1102@gmail.com
spring.mail.password=vjjrsiyabythxgcj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB

# Custom Upload Directory
app.upload.base-dir=C:/uploads
app.upload.bids-dir=${app.upload.base-dir}/bids
app.upload.tenders-dir=${app.upload.base-dir}/tenders
app.upload.clarification-dir=${app.upload.base-dir}/clarification


# Razorpay Configuration
razorpay.key.id=rzp_test_YOUR_KEY_HERE
razorpay.key.secret=YOUR_SECRET_HERE